-- Identity (docs/multi-user.md §2): Better Auth's tables, in their own
-- schema `identity` — its `session` (a sign-in) beside the SDK's `sessions`
-- (a conversation) in one schema would read as one thing. Generated by
-- `@better-auth/cli generate` for better-auth 1.7.7 with the magicLink,
-- organization, bearer, admin and apiKey plugins, then written in this
-- ledger's style: snake_case columns (the Drizzle mirror in storage/schema.ts
-- names them), timestamptz. Unused until an app turns identity on
-- (PhantomBackendConfig.identity).

create schema if not exists identity;

-- A person. `role` and the ban columns are the admin plugin's.
create table identity."user" (
  id             text primary key,
  name           text not null,
  email          text not null unique,
  email_verified boolean not null default false,
  image          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  role           text,
  banned         boolean default false,
  ban_reason     text,
  ban_expires    timestamptz
);

-- A sign-in: the token a cookie or bearer carries. `active_organization_id`
-- is the organization plugin's; `impersonated_by` the admin plugin's.
create table identity.session (
  id                     text primary key,
  expires_at             timestamptz not null,
  token                  text not null unique,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null,
  ip_address             text,
  user_agent             text,
  user_id                text not null references identity."user"(id) on delete cascade,
  active_organization_id text,
  impersonated_by        text
);
create index session_user_id_idx on identity.session (user_id);

-- One way a user signs in (a provider and its id); unused rows for magic
-- links, here for the methods that come later (password, OAuth).
create table identity.account (
  id                       text primary key,
  account_id               text not null,
  provider_id              text not null,
  user_id                  text not null references identity."user"(id) on delete cascade,
  access_token             text,
  refresh_token            text,
  id_token                 text,
  access_token_expires_at  timestamptz,
  refresh_token_expires_at timestamptz,
  scope                    text,
  password                 text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null
);
create index account_user_id_idx on identity.account (user_id);

-- A pending proof: the magic link's token, until it is clicked or expires.
create table identity.verification (
  id         text primary key,
  identifier text not null,
  value      text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index verification_identifier_idx on identity.verification (identifier);

create table identity.organization (
  id         text primary key,
  name       text not null,
  slug       text not null unique,
  logo       text,
  created_at timestamptz not null,
  metadata   text
);

-- user ↔ organization, with the role there (owner | admin | member).
create table identity.member (
  id              text primary key,
  organization_id text not null references identity.organization(id) on delete cascade,
  user_id         text not null references identity."user"(id) on delete cascade,
  role            text not null default 'member',
  created_at      timestamptz not null
);
create index member_organization_id_idx on identity.member (organization_id);
create index member_user_id_idx on identity.member (user_id);

create table identity.invitation (
  id              text primary key,
  organization_id text not null references identity.organization(id) on delete cascade,
  email           text not null,
  role            text,
  status          text not null default 'pending',
  expires_at      timestamptz not null,
  created_at      timestamptz not null default now(),
  inviter_id      text not null references identity."user"(id) on delete cascade
);
create index invitation_organization_id_idx on identity.invitation (organization_id);
create index invitation_email_idx on identity.invitation (email);

-- A long-lived key a program carries (x-api-key), resolving to its user
-- (`reference_id`). The key is stored hashed; `start` is its first chars.
create table identity.apikey (
  id                     text primary key,
  config_id              text not null default 'default',
  name                   text,
  start                  text,
  reference_id           text not null,
  prefix                 text,
  key                    text not null,
  refill_interval        integer,
  refill_amount          integer,
  last_refill_at         timestamptz,
  enabled                boolean default true,
  rate_limit_enabled     boolean default true,
  rate_limit_time_window integer default 86400000,
  rate_limit_max         integer default 10,
  request_count          integer default 0,
  remaining              integer,
  last_request           timestamptz,
  expires_at             timestamptz,
  created_at             timestamptz not null,
  updated_at             timestamptz not null,
  permissions            text,
  metadata               text
);
create index apikey_config_id_idx on identity.apikey (config_id);
create index apikey_reference_id_idx on identity.apikey (reference_id);
create index apikey_key_idx on identity.apikey (key);
